### ISSUE TITLE
Question: Use RadIO with TIFF/JPG

### ISSUE THREAD

**Issue by induswell** [analysiscenter/radio#10]
Hello experts:

Would I be able to use RadIO without the raw Dicom slices/files? I am working with CT scan images that have been cleaned and exported from Dicom to Tiff/Jpeg format. How would I use RadIO in this case? Please advise.

Thanks,

Indus

**Comment by akoryagin** [comment]
Hi, @induswell!

By default, ``RadIO`` does not support loading from `TIFF/JPEG`. Yet, there is a way
for you to make use of the framework. For this you need to write your own batch-class
with custom loader from `TIFF/JPEG`. This part could look something like

```
class CustomCTImagesBatch(CTImagesMaskedBatch):
   """ Your batch-class with custom loading action from TIFF/JPEG.
   """
   @action
   def load_from_images(self, images_folder):
       """ Load 3d-scans stored in JPEG.
    
       Assume each scan is stored in its own subfolder inside images_folder.
       """
       # initialize list of scans
       scans = []
         
       # iterate over items in batch
       for ix in batch.indices:
           # get folder for a specific scan
           item_folder = os.path.join(images_folder, ix)
        
	   # read all slices for a specific batch-item
 	   slices = read_jpegs(item_folder)	# your loader of jpegs for a scan should be here
        
	   # stack slices in 3d-scan and store them into the list
           scans.append(np.stack(slices))
       
       # concatenate scans-data into a skyscraper
       images = np.concatenate(scans)        

       # put scans-data in a batch
       self.load(fmt='ndarray', images=images, bounds=np.cumsum(np.array([len(a) for a in [[]] + scans])))
   
    return self
```
To get a better understanding of how to work with data in ``RadIO`` check out [this part ](https://analysiscenter.github.io/lung_cancer/intro/preprocessing.html#accessing-batch-components) of the documentation.

You can then chain the loader into a pipeline with other actions from ``RadIO``:

```
ds = Dataset(dataset_index, batch_class=CustomCTImagesBatch)
pipeline = (Pipeline()
            .load_from_images(folder)
            .resize(shape=(128, 256, 256))
            ...)
```
Best,
Alex.

**Comment by induswell** [comment]
Thanks for the quick response and tips, @akoryagin. I'll try your suggested approach.

**Comment by roman-kh** [comment]
The issue seem to be resolved, so I close it.
Feel free to reopen if needed.
