### ISSUE TITLE
Can't import radio after installing via pip3

### ISSUE THREAD

**Issue by trathpai** [analysiscenter/radio#12]
Python 3.6.3 |Anaconda custom (64-bit)| (default, Oct 13 2017, 12:02:49) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import radio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'radio'

Any known issues regarding this?

**Comment by AlexeyKozhevin** [comment]
Hello, trathpai!

We have checked that installation works in an empty virtual environment (in Linux) with command
`pip3 install git+https://github.com/analysiscenter/radio.git`, so we recommend trying to install `radio` again in accordance with the instruction. 

Best regards,
Alexey
