### ISSUE TITLE
Radio's version of dataset is out of date

### ISSUE THREAD

**Issue by johnny555** [analysiscenter/radio#17]
I'd like to add a some metrics (described here https://analysiscenter.github.io/dataset/api/dataset.models.metrics.html#dataset.models.metrics.Metrics) however it seems that the version of dataset that is shipped with radio is out of date. 

To reproduce, attempt to 
`import radio.dataset.models.metrics`

Returns:
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
/media/nvme/TRAIN/notebooks/PE/John's Exploration/trainModel.py in <module>()
----> 1 import radio.dataset.models.metrics

ModuleNotFoundError: No module named 'radio.dataset.models.metrics'
```

Expected:

nothing

**Comment by roman-kh** [comment]
The updated version of radio is under review now and will be realeased in the next few days.

**Comment by johnny555** [comment]
Thanks @roman-kh I don't see a pull request about it in Radio? Is it somewhere else? 
Any chance I could get a look at the early release?

**Comment by roman-kh** [comment]
`radio` is updated with the newest version of `batchflow`
