### ISSUE TITLE
Batch size > 1 images with different dimensions

### ISSUE THREAD

**Issue by jaysnanavati** [analysiscenter/radio#38]
Currently this is not possible, any pointers on how to work around this?

**Comment by roman-kh** [comment]
You need to create a custom batch class which stores an array of arrays with images.

**Comment by jaysnanavati** [comment]
hmm how would that work with the other functions that work on just a single array of images?

**Comment by roman-kh** [comment]
That would require some heavy refactoring. But overall in the long run this will simplify the code and the data structure.

**Comment by jaysnanavati** [comment]
Indeed, though what if we add the ability to pass in the same parameters as unifysampling to load? that way as soon as the image is loaded we can call unify to make sure all of them are the same dims?
________________________________

**Comment by roman-kh** [comment]
If you want just load images with different dimensions all you may need is a custom load action, which load images as is and then reshapes them to a common shape.

**Comment by jaysnanavati** [comment]
Yes, but I'd like to reuse existing implemented functions to do this :) what are your thoughts on having these parameters in the load function ?
________________________________

**Comment by jaysnanavati** [comment]
Ping??

**Comment by roman-kh** [comment]
Make a PR, please, and we will discuss your implementation.

**Comment by jaysnanavati** [comment]
Awesome! thanks for your help on this, appreciate it :)
