### ISSUE TITLE
Preprocessing resize

### ISSUE THREAD

**Issue by star-yar** [analysiscenter/radio#43]
Was following tutorial#1 and got the following exception on executing line (but works if remove resize part):
```
preprocessing = (Pipeline()                     # Initialize empty pipeline 
                 .load(fmt='raw')               # load data from disk
                 .resize(shape=(92, 256, 256))) # resize to shape (92, 256, 256)

batch = (luna_dataset >> preprocessing).next_batch(batch_size=3, shuffle=False)
```

Trows the same for 

```
preprocessing = preprocessing.resize(shape=(92, 256, 256)) # remember, nothing is executed here

batch = (luna_dataset >> preprocessing).next_batch(batch_size=3, shuffle=False)
```

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-17-fbc764c06c25> in <module>
----> 1 batch = (luna_dataset >> preprocessing).next_batch(batch_size=3, shuffle=False)

/usr/local/lib/python3.6/site-packages/radio/batchflow/batchflow/pipeline.py in next_batch(self, *args, **kwargs)
   1242                 self._lazy_run = args, kwargs
   1243                 self._batch_generator = self.gen_batch(*args, **kwargs)
-> 1244             batch_res = next(self._batch_generator)
   1245         else:
   1246             _kwargs = kwargs.copy()

/usr/local/lib/python3.6/site-packages/radio/batchflow/batchflow/pipeline.py in _gen_batch(self, *args, **kwargs)
   1212             for batch in batch_generator:
   1213                 try:
-> 1214                     batch_res = self.execute_for(batch)
   1215                 except SkipBatchException:
   1216                     pass

/usr/local/lib/python3.6/site-packages/radio/batchflow/batchflow/pipeline.py in execute_for(self, batch, new_loop)
    607             asyncio.set_event_loop(asyncio.new_event_loop())
    608         batch.pipeline = self
--> 609         batch_res = self._exec_all_actions(batch)
    610         batch_res.pipeline = self
    611         return batch_res

/usr/local/lib/python3.6/site-packages/radio/batchflow/batchflow/pipeline.py in _exec_all_actions(self, batch, action_list)
    579                     join_batches = None
    580 
--> 581                 batch = self._exec_one_action(batch, _action, _action_args, _action['kwargs'])
    582 
    583             batch.pipeline = self

/usr/local/lib/python3.6/site-packages/radio/batchflow/batchflow/pipeline.py in _exec_one_action(self, batch, action, args, kwargs)
    527                 batch.pipeline = self
    528                 action_method, _ = self._get_action_method(batch, action['name'])
--> 529                 batch = action_method(*args, **kwargs)
    530                 batch.pipeline = self
    531         return batch

/usr/local/lib/python3.6/site-packages/radio/batchflow/batchflow/decorators.py in _action_wrapper(action_self, *args, **kwargs)
     42                 action_self.pipeline.get_variable(_lock_name).acquire()
     43 
---> 44         _res = action_method(action_self, *args, **kwargs)
     45 
     46         if _use_lock is not None:

/usr/local/lib/python3.6/site-packages/radio/batchflow/batchflow/decorators.py in wrapped_method(self, *args, **kwargs)
    325                 x = wrap_with_async(self, args, kwargs)
    326             elif _target in ['threads', 't']:
--> 327                 x = wrap_with_threads(self, args, kwargs)
    328             elif _target in ['mpc', 'm']:
    329                 x = wrap_with_mpc(self, args, kwargs)

/usr/local/lib/python3.6/site-packages/radio/batchflow/batchflow/decorators.py in wrap_with_threads(self, args, kwargs)
    228                 cf.wait(futures, timeout=timeout, return_when=cf.ALL_COMPLETED)
    229 
--> 230             return _call_post_fn(self, post_fn, futures, args, full_kwargs)
    231 
    232         def wrap_with_mpc(self, args, kwargs):

/usr/local/lib/python3.6/site-packages/radio/batchflow/batchflow/decorators.py in _call_post_fn(self, post_fn, futures, args, kwargs)
    153                     traceback.print_tb(all_errors[0].__traceback__)
    154                 return self
--> 155             return post_fn(all_results, *args, **kwargs)
    156 
    157         def _prepare_args(self, args, kwargs):

/usr/local/lib/python3.6/site-packages/radio/preprocessing/ct_masked_batch.py in _post_rebuild(self, all_outputs, new_batch, **kwargs)
    970         """
    971         # TODO: process errors
--> 972         batch = super()._post_rebuild(all_outputs, new_batch, **kwargs)
    973         batch.nodules = self.nodules
    974         batch._rescale_spacing()  # pylint: disable=protected-access

/usr/local/lib/python3.6/site-packages/radio/preprocessing/ct_batch.py in _post_rebuild(self, all_outputs, new_batch, **kwargs)
   1071                     unify_spacing is performed.
   1072         """
-> 1073         self._reraise_worker_exceptions(all_outputs)
   1074 
   1075         new_bounds = np.cumsum([patient_shape[0] for _, patient_shape

/usr/local/lib/python3.6/site-packages/radio/preprocessing/ct_batch.py in _reraise_worker_exceptions(self, worker_outputs)
    865         if any_action_failed(worker_outputs):
    866             all_errors = self.get_errors(worker_outputs)
--> 867             raise RuntimeError("Failed parallelizing. Some of the workers failed with following errors: ", all_errors)
    868 
    869     def _post_custom_components(self, list_of_dicts, **kwargs):

RuntimeError: ('Failed parallelizing. Some of the workers failed with following errors: ', [LoweringError('Failed in object mode pipeline (step: object mode frontend)\nFailed in object mode pipeline (step: object mode backend)\n(<class \'numba.ir.StaticSetItem\'>, output_array[(slice(None, None, None), slice(None, None, None), slice(None, None, None))] = $196.21)\n\nFile "../../../../../usr/local/lib/python3.6/site-packages/radio/preprocessing/resize.py", line 124:\ndef resize_pil(input_array, output_array, res, axes_pairs=None, shape_resize=None,\n    <source elided>\n    # normalize result of resize (average over resizes with different pairs of axes)\n    output_array[:, :, :] /= len(axes_pairs)\n    ^\n\n[1] During: lowering "output_array[(slice(None, None, None), slice(None, None, None), slice(None, None, None))] = $196.21" at /usr/local/lib/python3.6/site-packages/radio/preprocessing/resize.py (124)\n-------------------------------------------------------------------------------\nThis should not have happened, a problem has occurred in Numba\'s internals.\n\nPlease report the error message and traceback, along with a minimal reproducer\nat: https://github.com/numba/numba/issues/new\n\nIf more help is needed please feel free to speak to the Numba core developers\ndirectly at: https://gitter.im/numba/numba\n\nThanks in advance for your help in improving Numba!\n\n',), LoweringError('Failed in object mode pipeline (step: object mode frontend)\nFailed in object mode pipeline (step: object mode backend)\n(<class \'numba.ir.StaticSetItem\'>, output_array[(slice(None, None, None), slice(None, None, None), slice(None, None, None))] = $196.21)\n\nFile "../../../../../usr/local/lib/python3.6/site-packages/radio/preprocessing/resize.py", line 124:\ndef resize_pil(input_array, output_array, res, axes_pairs=None, shape_resize=None,\n    <source elided>\n    # normalize result of resize (average over resizes with different pairs of axes)\n    output_array[:, :, :] /= len(axes_pairs)\n    ^\n\n[1] During: lowering "output_array[(slice(None, None, None), slice(None, None, None), slice(None, None, None))] = $196.21" at /usr/local/lib/python3.6/site-packages/radio/preprocessing/resize.py (124)\n-------------------------------------------------------------------------------\nThis should not have happened, a problem has occurred in Numba\'s internals.\n\nPlease report the error message and traceback, along with a minimal reproducer\nat: https://github.com/numba/numba/issues/new\n\nIf more help is needed please feel free to speak to the Numba core developers\ndirectly at: https://gitter.im/numba/numba\n\nThanks in advance for your help in improving Numba!\n\n',), LoweringError('Failed in object mode pipeline (step: object mode frontend)\nFailed in object mode pipeline (step: object mode backend)\n(<class \'numba.ir.StaticSetItem\'>, output_array[(slice(None, None, None), slice(None, None, None), slice(None, None, None))] = $196.21)\n\nFile "../../../../../usr/local/lib/python3.6/site-packages/radio/preprocessing/resize.py", line 124:\ndef resize_pil(input_array, output_array, res, axes_pairs=None, shape_resize=None,\n    <source elided>\n    # normalize result of resize (average over resizes with different pairs of axes)\n    output_array[:, :, :] /= len(axes_pairs)\n    ^\n\n[1] During: lowering "output_array[(slice(None, None, None), slice(None, None, None), slice(None, None, None))] = $196.21" at /usr/local/lib/python3.6/site-packages/radio/preprocessing/resize.py (124)\n-------------------------------------------------------------------------------\nThis should not have happened, a problem has occurred in Numba\'s internals.\n\nPlease report the error message and traceback, along with a minimal reproducer\nat: https://github.com/numba/numba/issues/new\n\nIf more help is needed please feel free to speak to the Numba core developers\ndirectly at: https://gitter.im/numba/numba\n\nThanks in advance for your help in improving Numba!\n\n',)])

**Comment by roman-kh** [comment]
This seems like a `numba` problem. Which numba version do you use?

**Comment by star-yar** [comment]
numba==0.44.1

**Comment by star-yar** [comment]
numba==0.44.1,

upgraded numba to 0.36.1
got the following exception:

```
Info about nodules location must be loaded before calling this method. Nothing happened.
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-9-fbc764c06c25> in <module>
----> 1 batch = (luna_dataset >> preprocessing).next_batch(batch_size=3, shuffle=False)

/usr/local/lib/python3.6/site-packages/radio/batchflow/batchflow/pipeline.py in next_batch(self, *args, **kwargs)
   1242                 self._lazy_run = args, kwargs
   1243                 self._batch_generator = self.gen_batch(*args, **kwargs)
-> 1244             batch_res = next(self._batch_generator)
   1245         else:
   1246             _kwargs = kwargs.copy()

/usr/local/lib/python3.6/site-packages/radio/batchflow/batchflow/pipeline.py in _gen_batch(self, *args, **kwargs)
   1212             for batch in batch_generator:
   1213                 try:
-> 1214                     batch_res = self.execute_for(batch)
   1215                 except SkipBatchException:
   1216                     pass

/usr/local/lib/python3.6/site-packages/radio/batchflow/batchflow/pipeline.py in execute_for(self, batch, new_loop)
    607             asyncio.set_event_loop(asyncio.new_event_loop())
    608         batch.pipeline = self
--> 609         batch_res = self._exec_all_actions(batch)
    610         batch_res.pipeline = self
    611         return batch_res

/usr/local/lib/python3.6/site-packages/radio/batchflow/batchflow/pipeline.py in _exec_all_actions(self, batch, action_list)
    579                     join_batches = None
    580 
--> 581                 batch = self._exec_one_action(batch, _action, _action_args, _action['kwargs'])
    582 
    583             batch.pipeline = self

/usr/local/lib/python3.6/site-packages/radio/batchflow/batchflow/pipeline.py in _exec_one_action(self, batch, action, args, kwargs)
    527                 batch.pipeline = self
    528                 action_method, _ = self._get_action_method(batch, action['name'])
--> 529                 batch = action_method(*args, **kwargs)
    530                 batch.pipeline = self
    531         return batch

/usr/local/lib/python3.6/site-packages/radio/batchflow/batchflow/decorators.py in _action_wrapper(action_self, *args, **kwargs)
     42                 action_self.pipeline.get_variable(_lock_name).acquire()
     43 
---> 44         _res = action_method(action_self, *args, **kwargs)
     45 
     46         if _use_lock is not None:

/usr/local/lib/python3.6/site-packages/radio/batchflow/batchflow/decorators.py in wrapped_method(self, *args, **kwargs)
    325                 x = wrap_with_async(self, args, kwargs)
    326             elif _target in ['threads', 't']:
--> 327                 x = wrap_with_threads(self, args, kwargs)
    328             elif _target in ['mpc', 'm']:
    329                 x = wrap_with_mpc(self, args, kwargs)

/usr/local/lib/python3.6/site-packages/radio/batchflow/batchflow/decorators.py in wrap_with_threads(self, args, kwargs)
    228                 cf.wait(futures, timeout=timeout, return_when=cf.ALL_COMPLETED)
    229 
--> 230             return _call_post_fn(self, post_fn, futures, args, full_kwargs)
    231 
    232         def wrap_with_mpc(self, args, kwargs):

/usr/local/lib/python3.6/site-packages/radio/batchflow/batchflow/decorators.py in _call_post_fn(self, post_fn, futures, args, kwargs)
    153                     traceback.print_tb(all_errors[0].__traceback__)
    154                 return self
--> 155             return post_fn(all_results, *args, **kwargs)
    156 
    157         def _prepare_args(self, args, kwargs):

/usr/local/lib/python3.6/site-packages/radio/preprocessing/ct_masked_batch.py in _post_rebuild(self, all_outputs, new_batch, **kwargs)
    974         batch._rescale_spacing()  # pylint: disable=protected-access
    975         if self.masks is not None:
--> 976             batch.create_mask()
    977         return batch
    978 

/usr/local/lib/python3.6/site-packages/radio/batchflow/batchflow/decorators.py in _action_wrapper(action_self, *args, **kwargs)
     42                 action_self.pipeline.get_variable(_lock_name).acquire()
     43 
---> 44         _res = action_method(action_self, *args, **kwargs)
     45 
     46         if _use_lock is not None:

/usr/local/lib/python3.6/site-packages/radio/preprocessing/ct_masked_batch.py in create_mask(self, mode)
    502         self.masks = np.zeros_like(self.images)
    503 
--> 504         center_pix = np.abs(self.nodules.nodule_center -
    505                             self.nodules.origin) / self.nodules.spacing
    506         radius_pix = np.rint(self.nodules.nodule_size / self.nodules.spacing / 2)

AttributeError: 'NoneType' object has no attribute 'nodule_center'
```

**Comment by star-yar** [comment]
Duplicate of #40
