### ISSUE TITLE
Loading binary masks

### ISSUE THREAD

**Issue by jwitos** [analysiscenter/radio#6]
Hi,

I'm having trouble understanding the idea of binary masks in your framework. If I understand correctly, the  data for training segmentation has to be in "nodule" format, which is restricted to rectangles (origin + diameter). Is it possible to load binary masks created manually and saved in raw formats? 

Best

**Comment by akoryagin** [comment]
@jwitos, thanks for the question!

Yes, it is possible, though a bit tricky. Firstly, you need a loader: a function that
fetches masks for a set of scans from your format:

```
def masks_fetcher_from_raw(batch, source, **kwargs):
	""" Your custom loader of masks
	"""
	masks_from_batch = source[batch.indices]  # fetch masks for items from specific batch
	return masks_from_batch
```
We also advise you to convert the masks to a set of nodules with `fetch_nodules_from_mask`. This will allow you to use `resize`,  `unify_spacing`, and train networks for detection. In all, your pipeline
will look like this:

```
from radio.dataset import Pipeline, F

pipeline = (Pipeline()
	    .load(fmt='raw')
	    .load(fmt='ndarray', masks=F(masks_fetcher_from_raw))
            .fetch_nodules_from_mask()
            .some_other_actions))
```
Note that `masks_fetcher_from_raw` is additionally wrapped  in `F`. This will ensure that the fetcher is executed **only when** a batch flows through your pipeline and real computations happen (read [here](https://analysiscenter.github.io/dataset/intro/named_expr.html) about this in more detail). 

Best,
Alex.

**Comment by paul-bd** [comment]
> Hi,
> 
> I'm having trouble understanding the idea of binary masks in your framework. If I understand correctly, the data for training segmentation has to be in "nodule" format, which is restricted to rectangles (origin + diameter). Is it possible to load binary masks created manually and saved in raw formats?
> 
> Best

Hey,
have you find a solution using a fetcher from raw ? 
I am facing the same issue, with mask in nifti format. 
Best regard.
Paul
